### ISSUE TITLE
pollInterval is not defined

### ISSUE THREAD

**Issue by CerberusVelvet** [DanTheMan827/homebridge-ds18b20#13]
Just installed on a clean build. Homebridge bombs out with error: ReferenceError: pollInterval is not defined

config is as per readme

**Comment by marcelkordek** [comment]
Hi, the Error is in index.js:28

```
Wring -> if (pollInterval)
Correct ->  if (this.pollInterval)
```

Greetings

**Comment by DanTheMan827** [comment]
Sorry about that
