### ISSUE TITLE
Offset not working properly

### ISSUE THREAD

**Issue by fascpt** [DanTheMan827/homebridge-ds18b20#17]
Whenever I configure an offset (say "1.3") the value is adjusted for only a few seconds, only to return to the original value without offset.

This is my config:
	{
	    "accessory": "DS18B20",
	    "name": "DS18B20",
	    "device": "28-0517c0e696ff",
	    "pollInterval": 5000,
	    "offsetC": 1.3
	}

**Comment by DanTheMan827** [comment]
Fixed. download the latest version again
