### ISSUE TITLE
Can a fahrenheit conversion be added?

### ISSUE THREAD

**Issue by adamrgolf** [DanTheMan827/homebridge-ds18b20#3]
Just wondering if this could show the temperature in fahrenheit instead of celcius, or perhaps an option to choose which one you'd like displayed. What do you think?

Thanks!

Adam

**Comment by DanTheMan827** [comment]
As far as I know homebridge only accepts Celsius as a temperature...

For me Siri automatically translates that to Fahrenheit so maybe the temperature you receive is based on the locale that your device is set to?

**Comment by adamrgolf** [comment]
Ah, thank you. Siri does infact return the temperature in Fahrenheit. I was just a bit confused since the MyTouchHome app only showed in in Celcius. Thanks!!
