### ISSUE TITLE
refresh time

### ISSUE THREAD

**Issue by firaskhf** [DanTheMan827/homebridge-ds18b20#7]
Hi There, I'm new to Raspberry pi and Homebridge.
The sensor is not updating until i close and reopen the home app in my phone, therefore i'm unable to automate a GPIO switch based on the temperature value. Is there any solution for that?
thank you.

**Comment by ehusar** [comment]
I wonder if you could use homebridge-cmdswitch2.  You can set a pooling value that would help run something periodically.

**Comment by lfiocco** [comment]
Any news on this?

**Comment by toshibochan** [comment]
this is working?

**Comment by firaskhf** [comment]
sorry for the delay but how can i add my homebridge-ds18b20 plugin to the homebridge-cmdswitch2 ?
